create extension if not exists pgcrypto with schema extensions;

create table if not exists public.skill_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  username_norm text not null unique,
  password_salt text not null,
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  force_password_change boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.skill_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.skill_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.skill_access_tokens (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.skill_users(id) on delete cascade,
  label text not null,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create table if not exists public.private_skills (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.skill_users(id) on delete cascade,
  slug text not null,
  name text not null,
  description text not null,
  category text not null,
  source text not null default 'user-upload',
  object_path text not null unique,
  package_sha256 text not null,
  file_count integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, slug)
);

create table if not exists public.skill_auth_events (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  username_norm text not null,
  created_at timestamptz not null default now()
);

create index if not exists skill_sessions_owner_idx on public.skill_sessions(owner_id);
create index if not exists skill_sessions_expiry_idx on public.skill_sessions(expires_at);
create index if not exists skill_tokens_owner_idx on public.skill_access_tokens(owner_id);
create index if not exists private_skills_owner_idx on public.private_skills(owner_id);
create index if not exists skill_auth_events_lookup_idx on public.skill_auth_events(ip_hash, username_norm, created_at);

alter table public.skill_users enable row level security;
alter table public.skill_sessions enable row level security;
alter table public.skill_access_tokens enable row level security;
alter table public.private_skills enable row level security;
alter table public.skill_auth_events enable row level security;

revoke all on public.skill_users from anon, authenticated;
revoke all on public.skill_sessions from anon, authenticated;
revoke all on public.skill_access_tokens from anon, authenticated;
revoke all on public.private_skills from anon, authenticated;
revoke all on public.skill_auth_events from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('private-skills', 'private-skills', false, 6291456, array['application/zip'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- No client policies are created for storage.objects. Only the Edge Function's
-- server-side secret key can access the private bucket, and it checks owner_id.
